#===================================================
#  === Oauth2 Client  ===
#===================================================

spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:***************************************.com
            client-secret: ********************************
            scope:
            - email
            - profile
            
            
            
            
            